New sandbox:ips call
SalesforceCommerceCloud/sfcc-ci pull request #187
Opened 2020-11-11 21:33 UTC by EvilJordan

Added standalone `sandbox:ips` CLI call to list both inbound **AND** outbound IPs with optional JSON output.

When requesting JSON output, resultant output wraps in key for easy parsing:
```
{"inbound":["3.210.241.243","3.212.83.232","18.206.49.158","34.203.78.166","3.208.56.208","54.147.234.135"]}
{"outbound":["3.220.190.116","34.195.33.38","3.218.239.11"]}
```

2020-11-12 03:28 UTC, Gektorian commented
Hi @EvilJordan, do you think we could also update Readme.MD with a new endpoint and example of usage for how it is for other endpoints?

2020-11-12 21:19 UTC, sholsinger requested changes
Thanks for your awesome contribution Jordan. I'd not assume that 'ips' in that context would be 100% clear to all users. :)

2020-11-12 21:19 UTC, sholsinger commented on README.md
> +    sandbox:ips [options]                                           List inbound and outbound ips for sandboxes
```suggestion
    sandbox:ips [options]                                           List inbound and outbound IP addresses for sandboxes
```

2020-11-12 21:19 UTC, sholsinger commented on cli.js
> +    .description('List inbound and outbound ips for sandboxes')
```suggestion
    .description('List inbound and outbound IP addresses for sandboxes')
```

2020-11-12 22:00 UTC, sholsinger approved these changes

2020-11-13 06:42 UTC, hnestmann commented
Thanks for your contribution @EvilJordan I really love that you guys participate. Do I see this right that  this filters information from the sandbox:get call? If that is the case, would you think that sandbox:get:ips  would be an idea too? We could have other useful lookups such  as sandbox:get:hostname

2020-11-13 06:51 UTC, EvilJordan commented
@hnestmann This is a standalone call that draws from (and slightly extends) the existent `printInboundIPs()` method that seems to only be called during the `sandbox:alias:list` and `sandbox:alias:add` methods...

I'm all for having parity of `sfcc-ci` with the available API methods as listed in Swagger! The more, the better!

2020-11-13 07:17 UTC, hnestmann commented
@EvilJordan Cool, I see. Let's wait @tobiaslohr s thoughts :)

2021-02-08 17:20 UTC, EvilJordan commented
Bumping this... just had a painful client call trying to walk them through gaining access to the Swagger UI, when all they had used before was sfcc-ci, in order to retrieve IPs.

I think this would be a very useful addition to the toolkit!

2021-02-08 23:19 UTC, Gektorian approved these changes

2021-05-26 12:57 UTC, tobiaslohr approved these changes

2021-05-26 12:57 UTC, tobiaslohr commented
Thanks a lot @EvilJordan for contributing! Sorry for the delay, we had to fix a CircleCI related build issue first.

2021-05-26 12:58 UTC, merged